baseURL: "https://s1mn.io/"
languageCode: "en-gb"
title: "Simon Whitaker"
theme: "charlolamode"

menu:
  main: []

params:
  ShowBreadCrumbs: false
  profileMode:
    title: Simon Whitaker
    description: |

      Hello, I'm Simon. I build software, and teams that build software.
    imageUrl: "/images/simon.jpg"
    imageTitle: Simon Whitaker
  socialIcons:
    - name: mastodon
      url: "https://toot.io/@s1mn"
    - name: github
      url: "https://github.com/simonwhitaker"
    - name: linkedin
      url: "https://www.linkedin.com/in/s1mn/"
