baseURL: "https://s1mn.io/"
languageCode: "en-gb"
title: "s1mn"
theme: "charlolamode"

menu:
  main: []

params:
  profileMode:
    title: Simon Whitaker
    description: |

      Hello, I'm Simon. I'm a software engineer.
    imageUrl: "/images/simon.jpg"
    imageTitle: Simon Whitaker
  socialIcons:
    - name: mastodon
      url: "https://toot.io/@s1mn"
    - name: github
      url: "https://github.com/simonwhitaker"
    - name: linkedin
      url: "https://www.linkedin.com/in/simonwhitakeruk/"
